version: "3.8"
services:
    db:
        image: "mysql:5.7"
        networks:
            - "wpnet"
        volumes:
            - "db_data:/var/lib/mysql"
        restart: "always"
        environment:
            MYSQL_ROOT_PASSWORD: "wordpress"
            MYSQL_DATABASE: "wordpress"
            MYSQL_USER: "wordpress"
            MYSQL_PASSWORD: "wordpress"

    wordpress:
        depends_on:
            - "db"
        image: "wordpress:latest"
        networks:
            - "wpnet"
        ports:
            - "8000:80"
        volumes:
            - ".:/var/www/html/wp-content/plugins/tier-template-generator"
        restart: "always"
        environment:
            WORDPRESS_DB_HOST: "db:3306"
            WORDPRESS_DB_USER: "wordpress"
            WORDPRESS_DB_PASSWORD: "wordpress"
            WORDPRESS_DB_NAME: "wordpress"
networks:
    wpnet:
        driver: "bridge"
volumes:
    db_data:
        driver: "local"
    wp_data:
        driver: "local"
